// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddPlayerArgs {
    pub game_id: u64,
    pub user_id: __sdk::Identity,
}

impl From<AddPlayerArgs> for super::Reducer {
    fn from(args: AddPlayerArgs) -> Self {
        Self::AddPlayer {
            game_id: args.game_id,
            user_id: args.user_id,
        }
    }
}

impl __sdk::InModule for AddPlayerArgs {
    type Module = super::RemoteModule;
}

pub struct AddPlayerCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_player`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_player {
    /// Request that the remote module invoke the reducer `add_player` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_add_player`] callbacks.
    fn add_player(&self, game_id: u64, user_id: __sdk::Identity) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `add_player`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AddPlayerCallbackId`] can be passed to [`Self::remove_on_add_player`]
    /// to cancel the callback.
    fn on_add_player(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &__sdk::Identity) + Send + 'static,
    ) -> AddPlayerCallbackId;
    /// Cancel a callback previously registered by [`Self::on_add_player`],
    /// causing it not to run in the future.
    fn remove_on_add_player(&self, callback: AddPlayerCallbackId);
}

impl add_player for super::RemoteReducers {
    fn add_player(&self, game_id: u64, user_id: __sdk::Identity) -> __sdk::Result<()> {
        self.imp
            .call_reducer("add_player", AddPlayerArgs { game_id, user_id })
    }
    fn on_add_player(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &__sdk::Identity) + Send + 'static,
    ) -> AddPlayerCallbackId {
        AddPlayerCallbackId(self.imp.on_reducer(
            "add_player",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::AddPlayer { game_id, user_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, game_id, user_id)
            }),
        ))
    }
    fn remove_on_add_player(&self, callback: AddPlayerCallbackId) {
        self.imp.remove_on_reducer("add_player", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `add_player`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_add_player {
    /// Set the call-reducer flags for the reducer `add_player` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn add_player(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_add_player for super::SetReducerFlags {
    fn add_player(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("add_player", flags);
    }
}
