// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddToGuildArgs {
    pub guild_id: u64,
    pub friend_code: i32,
}

impl From<AddToGuildArgs> for super::Reducer {
    fn from(args: AddToGuildArgs) -> Self {
        Self::AddToGuild {
            guild_id: args.guild_id,
            friend_code: args.friend_code,
        }
    }
}

impl __sdk::InModule for AddToGuildArgs {
    type Module = super::RemoteModule;
}

pub struct AddToGuildCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_to_guild`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_to_guild {
    /// Request that the remote module invoke the reducer `add_to_guild` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_add_to_guild`] callbacks.
    fn add_to_guild(&self, guild_id: u64, friend_code: i32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `add_to_guild`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AddToGuildCallbackId`] can be passed to [`Self::remove_on_add_to_guild`]
    /// to cancel the callback.
    fn on_add_to_guild(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &i32) + Send + 'static,
    ) -> AddToGuildCallbackId;
    /// Cancel a callback previously registered by [`Self::on_add_to_guild`],
    /// causing it not to run in the future.
    fn remove_on_add_to_guild(&self, callback: AddToGuildCallbackId);
}

impl add_to_guild for super::RemoteReducers {
    fn add_to_guild(&self, guild_id: u64, friend_code: i32) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "add_to_guild",
            AddToGuildArgs {
                guild_id,
                friend_code,
            },
        )
    }
    fn on_add_to_guild(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &i32) + Send + 'static,
    ) -> AddToGuildCallbackId {
        AddToGuildCallbackId(self.imp.on_reducer(
            "add_to_guild",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::AddToGuild {
                                    guild_id,
                                    friend_code,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, guild_id, friend_code)
            }),
        ))
    }
    fn remove_on_add_to_guild(&self, callback: AddToGuildCallbackId) {
        self.imp.remove_on_reducer("add_to_guild", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `add_to_guild`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_add_to_guild {
    /// Set the call-reducer flags for the reducer `add_to_guild` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn add_to_guild(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_add_to_guild for super::SetReducerFlags {
    fn add_to_guild(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("add_to_guild", flags);
    }
}
