// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateGameArgs {
    pub guild_id: u64,
}

impl From<CreateGameArgs> for super::Reducer {
    fn from(args: CreateGameArgs) -> Self {
        Self::CreateGame {
            guild_id: args.guild_id,
        }
    }
}

impl __sdk::InModule for CreateGameArgs {
    type Module = super::RemoteModule;
}

pub struct CreateGameCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_game`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_game {
    /// Request that the remote module invoke the reducer `create_game` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_create_game`] callbacks.
    fn create_game(&self, guild_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `create_game`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CreateGameCallbackId`] can be passed to [`Self::remove_on_create_game`]
    /// to cancel the callback.
    fn on_create_game(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> CreateGameCallbackId;
    /// Cancel a callback previously registered by [`Self::on_create_game`],
    /// causing it not to run in the future.
    fn remove_on_create_game(&self, callback: CreateGameCallbackId);
}

impl create_game for super::RemoteReducers {
    fn create_game(&self, guild_id: u64) -> __sdk::Result<()> {
        self.imp
            .call_reducer("create_game", CreateGameArgs { guild_id })
    }
    fn on_create_game(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> CreateGameCallbackId {
        CreateGameCallbackId(self.imp.on_reducer(
            "create_game",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::CreateGame { guild_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, guild_id)
            }),
        ))
    }
    fn remove_on_create_game(&self, callback: CreateGameCallbackId) {
        self.imp.remove_on_reducer("create_game", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `create_game`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_create_game {
    /// Set the call-reducer flags for the reducer `create_game` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn create_game(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_game for super::SetReducerFlags {
    fn create_game(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("create_game", flags);
    }
}
