// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use super::guild_user_type::GuildUser;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `guild_user`.
///
/// Obtain a handle from the [`GuildUserTableAccess::guild_user`] method on [`super::RemoteTables`],
/// like `ctx.db.guild_user()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.guild_user().on_insert(...)`.
pub struct GuildUserTableHandle<'ctx> {
    imp: __sdk::TableHandle<GuildUser>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `guild_user`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GuildUserTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GuildUserTableHandle`], which mediates access to the table `guild_user`.
    fn guild_user(&self) -> GuildUserTableHandle<'_>;
}

impl GuildUserTableAccess for super::RemoteTables {
    fn guild_user(&self) -> GuildUserTableHandle<'_> {
        GuildUserTableHandle {
            imp: self.imp.get_table::<GuildUser>("guild_user"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GuildUserInsertCallbackId(__sdk::CallbackId);
pub struct GuildUserDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GuildUserTableHandle<'ctx> {
    type Row = GuildUser;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GuildUser> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GuildUserInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GuildUserInsertCallbackId {
        GuildUserInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GuildUserInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GuildUserDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GuildUserDeleteCallbackId {
        GuildUserDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GuildUserDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GuildUser>("guild_user");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<GuildUser>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GuildUser>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
