// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#![allow(unused, clippy::all)]
use super::guild_type::Guild;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `guild`.
///
/// Obtain a handle from the [`GuildTableAccess::guild`] method on [`super::RemoteTables`],
/// like `ctx.db.guild()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.guild().on_insert(...)`.
pub struct GuildTableHandle<'ctx> {
    imp: __sdk::TableHandle<Guild>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `guild`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GuildTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GuildTableHandle`], which mediates access to the table `guild`.
    fn guild(&self) -> GuildTableHandle<'_>;
}

impl GuildTableAccess for super::RemoteTables {
    fn guild(&self) -> GuildTableHandle<'_> {
        GuildTableHandle {
            imp: self.imp.get_table::<Guild>("guild"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GuildInsertCallbackId(__sdk::CallbackId);
pub struct GuildDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GuildTableHandle<'ctx> {
    type Row = Guild;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Guild> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GuildInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GuildInsertCallbackId {
        GuildInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GuildInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GuildDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GuildDeleteCallbackId {
        GuildDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GuildDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Guild>("guild");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct GuildUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GuildTableHandle<'ctx> {
    type UpdateCallbackId = GuildUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GuildUpdateCallbackId {
        GuildUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GuildUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Guild>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Guild>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `guild`,
/// which allows point queries on the field of the same name
/// via the [`GuildIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.guild().id().find(...)`.
pub struct GuildIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Guild, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GuildTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `guild`.
    pub fn id(&self) -> GuildIdUnique<'ctx> {
        GuildIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GuildIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Guild> {
        self.imp.find(col_val)
    }
}
