// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RenameSelfArgs {
    pub new_name: String,
}

impl From<RenameSelfArgs> for super::Reducer {
    fn from(args: RenameSelfArgs) -> Self {
        Self::RenameSelf {
            new_name: args.new_name,
        }
    }
}

impl __sdk::InModule for RenameSelfArgs {
    type Module = super::RemoteModule;
}

pub struct RenameSelfCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `rename_self`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait rename_self {
    /// Request that the remote module invoke the reducer `rename_self` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_rename_self`] callbacks.
    fn rename_self(&self, new_name: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `rename_self`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RenameSelfCallbackId`] can be passed to [`Self::remove_on_rename_self`]
    /// to cancel the callback.
    fn on_rename_self(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> RenameSelfCallbackId;
    /// Cancel a callback previously registered by [`Self::on_rename_self`],
    /// causing it not to run in the future.
    fn remove_on_rename_self(&self, callback: RenameSelfCallbackId);
}

impl rename_self for super::RemoteReducers {
    fn rename_self(&self, new_name: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("rename_self", RenameSelfArgs { new_name })
    }
    fn on_rename_self(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> RenameSelfCallbackId {
        RenameSelfCallbackId(self.imp.on_reducer(
            "rename_self",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::RenameSelf { new_name },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, new_name)
            }),
        ))
    }
    fn remove_on_rename_self(&self, callback: RenameSelfCallbackId) {
        self.imp.remove_on_reducer("rename_self", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `rename_self`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_rename_self {
    /// Set the call-reducer flags for the reducer `rename_self` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn rename_self(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_rename_self for super::SetReducerFlags {
    fn rename_self(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("rename_self", flags);
    }
}
