// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReplacePlayerArgs {
    pub player_id: u64,
    pub user_id: __sdk::Identity,
}

impl From<ReplacePlayerArgs> for super::Reducer {
    fn from(args: ReplacePlayerArgs) -> Self {
        Self::ReplacePlayer {
            player_id: args.player_id,
            user_id: args.user_id,
        }
    }
}

impl __sdk::InModule for ReplacePlayerArgs {
    type Module = super::RemoteModule;
}

pub struct ReplacePlayerCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `replace_player`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait replace_player {
    /// Request that the remote module invoke the reducer `replace_player` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_replace_player`] callbacks.
    fn replace_player(&self, player_id: u64, user_id: __sdk::Identity) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `replace_player`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ReplacePlayerCallbackId`] can be passed to [`Self::remove_on_replace_player`]
    /// to cancel the callback.
    fn on_replace_player(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &__sdk::Identity) + Send + 'static,
    ) -> ReplacePlayerCallbackId;
    /// Cancel a callback previously registered by [`Self::on_replace_player`],
    /// causing it not to run in the future.
    fn remove_on_replace_player(&self, callback: ReplacePlayerCallbackId);
}

impl replace_player for super::RemoteReducers {
    fn replace_player(&self, player_id: u64, user_id: __sdk::Identity) -> __sdk::Result<()> {
        self.imp
            .call_reducer("replace_player", ReplacePlayerArgs { player_id, user_id })
    }
    fn on_replace_player(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &__sdk::Identity) + Send + 'static,
    ) -> ReplacePlayerCallbackId {
        ReplacePlayerCallbackId(self.imp.on_reducer(
            "replace_player",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ReplacePlayer { player_id, user_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, player_id, user_id)
            }),
        ))
    }
    fn remove_on_replace_player(&self, callback: ReplacePlayerCallbackId) {
        self.imp.remove_on_reducer("replace_player", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `replace_player`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_replace_player {
    /// Set the call-reducer flags for the reducer `replace_player` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn replace_player(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_replace_player for super::SetReducerFlags {
    fn replace_player(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("replace_player", flags);
    }
}
